# Generated by Django 6.0.1 on 2026-01-28 00:00

from django.db import migrations
from django.db.models import F


def backfill_positions(apps, schema_editor):
    QuotationItem = apps.get_model("quotations", "QuotationItem")

    # We will ensure: for each quotation, positions become 1..N in a stable order.
    # Stable order = existing position (if any) then id.
    quotation_ids = (
        QuotationItem.objects.values_list("quotation_id", flat=True).distinct()
    )

    for qid in quotation_ids.iterator():
        items = list(
            QuotationItem.objects.filter(quotation_id=qid)
            .order_by("position", "id")
            .values_list("id", "position")
        )

        # Assign sequential positions starting at 1
        new_pos = 1
        for item_id, _old_pos in items:
            QuotationItem.objects.filter(id=item_id).update(position=new_pos)
            new_pos += 1


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0006_alter_quotationitem_options_quotationitem_position_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_positions, migrations.RunPython.noop),
    ]
