# Generated by Django 6.0.1 on 2026-02-05 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_tasks', '0007_jobtaskassetlink_property_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_works', to=settings.AUTH_USER_MODEL)),
                ('job_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='job_tasks.jobtask')),
            ],
            options={
                'indexes': [models.Index(fields=['start'], name='scheduling__start_721091_idx'), models.Index(fields=['end'], name='scheduling__end_875a1d_idx')],
            },
        ),
    ]
