# Generated by Django 6.0.1 on 2026-01-20 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codes', '0011_alter_dropdownoption_options'),
        ('properties', '0009_property_sor_site_id_property_strata_plan'),
        ('quotations', '0004_remove_quotation_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_type', models.CharField(choices=[('annual', 'Annual'), ('biannual', 'Bi-Annual'), ('monthly', 'Monthly')], max_length=20)),
                ('month_due', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('work_order_number', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_routines_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_routines', to='quotations.quotation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property')),
            ],
            options={
                'ordering': ['quotation_id', 'month_due', 'routine_type'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efsm_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.code')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='routines.serviceroutine')),
                ('source_quotation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routine_items', to='quotations.quotationitem')),
            ],
            options={
                'ordering': ['efsm_code__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceroutine',
            constraint=models.UniqueConstraint(fields=('quotation', 'routine_type', 'month_due'), name='uniq_routine_type_and_month_per_quotation'),
        ),
        migrations.AddConstraint(
            model_name='serviceroutineitem',
            constraint=models.UniqueConstraint(fields=('routine', 'efsm_code'), name='uniq_code_per_routine'),
        ),
    ]
