# Generated by Django 6.0.1 on 2026-01-20 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_sor_site_id_property_strata_plan'),
        ('quotations', '0004_remove_quotation_accepted_at_and_more'),
        ('routines', '0002_alter_serviceroutine_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceroutine',
            options={'ordering': ['quotation_id', 'month_due', 'routine_type']},
        ),
        migrations.RemoveConstraint(
            model_name='serviceroutine',
            name='uniq_routine_type_and_month_per_quotation',
        ),
        migrations.RenameField(
            model_name='serviceroutine',
            old_name='service_month',
            new_name='month_due',
        ),
        migrations.AddConstraint(
            model_name='serviceroutine',
            constraint=models.UniqueConstraint(fields=('quotation', 'routine_type', 'month_due'), name='uniq_routine_type_and_month_per_quotation'),
        ),
    ]
