# Generated by Django 6.0.1 on 2026-01-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_alter_serviceroutine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceroutine',
            name='routine_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('biannual', 'Bi-Annual'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20),
        ),
    ]
