# Generated by Django 6.0.1 on 2026-01-22 09:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0011_alter_dropdownoption_options'),
        ('properties', '0009_property_sor_site_id_property_strata_plan'),
        ('quotations', '0005_quotation_calc_afss_charge_and_more'),
        ('routines', '0004_alter_serviceroutine_routine_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceroutine',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='serviceroutineitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='serviceroutine',
            name='uniq_routine_type_and_month_per_quotation',
        ),
        migrations.RemoveConstraint(
            model_name='serviceroutineitem',
            name='uniq_code_per_routine',
        ),
        migrations.AddField(
            model_name='serviceroutineitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serviceroutineitem',
            name='custom_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='month_due',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_routines', to='quotations.quotation'),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='routine_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('biannual', 'Bi-Annual'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_routines', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='work_order_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceroutineitem',
            name='efsm_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_routine_items', to='codes.code'),
        ),
        migrations.AlterField(
            model_name='serviceroutineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceroutineitem',
            name='source_quotation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_routine_items', to='quotations.quotationitem'),
        ),
    ]
