# Generated by Django 6.0.1 on 2026-01-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0011_alter_dropdownoption_options"),
        ("quotations", "0006_alter_quotationitem_options_quotationitem_position_and_more"),
        ("routines", "0005_alter_serviceroutine_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceroutineitem",
            options={"ordering": ["position", "id"]},
        ),
        migrations.AddField(
            model_name="serviceroutineitem",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        # IMPORTANT: Do NOT add the unique constraint here.
        # We backfill positions first in 0007, then add the constraint.
    ]
