# Generated by Django 6.0.1 on 2026-01-27 23:42

import django.db.models.constraints
from django.db import migrations, models


def forwards_backfill_positions(apps, schema_editor):
    ServiceRoutineItem = apps.get_model("routines", "ServiceRoutineItem")

    routine_ids = (
        ServiceRoutineItem.objects
        .order_by()
        .values_list("routine_id", flat=True)
        .distinct()
    )

    for rid in routine_ids:
        items = list(
            ServiceRoutineItem.objects
            .filter(routine_id=rid)
            .order_by("position", "id")
        )

        # Renumber 1..N to guarantee uniqueness per routine
        for i, item in enumerate(items, start=1):
            if item.position != i:
                ServiceRoutineItem.objects.filter(pk=item.pk).update(position=i)


def backwards_unset_positions(apps, schema_editor):
    ServiceRoutineItem = apps.get_model("routines", "ServiceRoutineItem")
    ServiceRoutineItem.objects.all().update(position=0)


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0006_alter_serviceroutineitem_options_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_backfill_positions, backwards_unset_positions),
        migrations.AddConstraint(
            model_name="serviceroutineitem",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("routine", "position"),
                name="uniq_service_routine_item_position",
            ),
        ),
    ]
