# Generated by Django 6.0.1 on 2026-01-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_alter_serviceroutineitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serviceroutineitem',
            name='uniq_service_routine_item_position',
        ),
    ]
