# Generated by Django 6.0.1 on 2026-01-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0008_remove_serviceroutine_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceroutine',
            name='annual_man_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='half_yearly_man_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='monthly_man_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='monthly_run_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceroutine',
            name='monthly_week_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
