# Generated by Django 6.0.1 on 2026-01-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0009_alter_serviceroutine_annual_man_hours_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serviceroutineitem',
            name='uniq_service_routine_item_position',
        ),
    ]
