# Generated by Django 6.0.1 on 2026-02-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0007_jobtaskassetlink_property_asset_and_more'),
        ('routines', '0010_remove_serviceroutineitem_uniq_service_routine_item_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceroutine',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_routines', to='job_tasks.jobservicetype'),
        ),
    ]
