# Generated by Django 6.0.1 on 2026-01-27 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_accounting_id'),
        ('job_tasks', '0001_initial'),
        ('properties', '0010_alter_property_options_property_afss_number_and_more'),
        ('routines', '0005_alter_serviceroutine_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='property',
        ),
        migrations.AddField(
            model_name='jobtask',
            name='additional_technicians',
            field=models.ManyToManyField(blank=True, related_name='job_tasks_additional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='service_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tasks_primary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tasks', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tasks', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='service_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tasks', to='routines.serviceroutine'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tasks', to='job_tasks.jobservicetype'),
        ),
        migrations.CreateModel(
            name='JobTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('job_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job_tasks.jobtask')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
