# Generated by Django 6.0.1 on 2026-01-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0002_jobservicetype_remove_jobtask_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtask',
            name='acknowledgement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='admin_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='client_acknowledgement',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='service_time',
            field=models.CharField(blank=True, help_text='e.g. 8.30am - 10.45am', max_length=50),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='technician_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='work_order_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
