# Generated by Django 6.0.1 on 2026-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0003_jobtask_acknowledgement_date_jobtask_admin_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtask',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='admin_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='client_acknowledgement',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='service_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='status',
            field=models.CharField(choices=[('open', 'Unscheduled'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='technician_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='work_order_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
