# Generated by Django 6.0.1 on 2026-01-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0004_remove_jobtask_due_date_alter_jobtask_admin_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtask',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
