# Generated by Django 6.0.1 on 2026-01-29 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0005_jobtask_finish_time_jobtask_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTaskAssetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_asset_links', to='job_tasks.jobtask')),
            ],
            options={
                'verbose_name': 'Job Task Asset Link',
                'verbose_name_plural': 'Job Task Asset Links',
            },
        ),
    ]
