# Generated by Django 6.0.1 on 2026-01-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0006_jobtaskassetlink'),
        ('properties', '0011_propertyasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtaskassetlink',
            name='property_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_task_links', to='properties.propertyasset'),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='property_assets',
            field=models.ManyToManyField(blank=True, related_name='job_tasks', through='job_tasks.JobTaskAssetLink', to='properties.propertyasset'),
        ),
        migrations.AddConstraint(
            model_name='jobtaskassetlink',
            constraint=models.UniqueConstraint(fields=('job_task', 'property_asset'), name='uq_jobtask_propertyasset_link'),
        ),
    ]
