# Generated by Django 6.0.1 on 2026-02-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0007_jobtaskassetlink_property_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtask',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
    ]
