# Generated by Django 6.0.1 on 2026-02-06 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tasks', '0008_jobtask_is_all_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtask',
            name='parent_job',
            field=models.ForeignKey(blank=True, help_text='If set, this task is a child of a parent job (shared assets + shared site notes).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_jobs', to='job_tasks.jobtask'),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='shared_site_notes',
            field=models.TextField(blank=True, default='', help_text='Shared site notes for this job group (stored on the parent job).'),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='technician_job_notes',
            field=models.TextField(blank=True, default='', help_text='Technician-specific job notes (per scheduled task).'),
        ),
    ]
