# Generated by Django 6.0.1 on 2026-01-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_name_customer_customer_name_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='notes',
            new_name='access_details',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='zip_code',
            new_name='post_code',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='afss_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='property',
            name='fire_coordinator',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='fire_coordinator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='fire_coordinator_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='levels_above_ground',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='levels_below_ground',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='site_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='site_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='site_uid',
            field=models.CharField(blank=True, editable=False, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='technician_notes',
            field=models.TextField(blank=True),
        ),
    ]
