# Generated by Django 6.0.1 on 2026-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_notes_property_access_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='access_details',
            field=models.CharField(blank=True, choices=[('unrestricted', 'Unrestricted'), ('reception', 'Reception Access Required'), ('key', 'Key Required'), ('security', 'Security Desk'), ('after_hours', 'After Hours Only'), ('other', 'Other')], max_length=50),
        ),
    ]
