# Generated by Django 6.0.1 on 2026-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_access_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='access_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='access_details',
            field=models.CharField(blank=True, choices=[('unrestricted', 'Unrestricted'), ('Office', 'Keys Held In Office'), ('key', 'Keys Required'), ('site_contact', 'Site Contact'), ('lock_box', 'Lock Box Code'), ('other', 'Other')], max_length=50),
        ),
    ]
