# Generated by Django 6.0.1 on 2026-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_access_code_alter_property_access_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='site_uid',
        ),
        migrations.AddField(
            model_name='property',
            name='site_id',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='access_details',
            field=models.CharField(blank=True, choices=[('unrestricted', 'Unrestricted'), ('office', 'Keys Held In Office'), ('key', 'Keys Required'), ('site_contact', 'Site Contact'), ('lock_box', 'Lock Box Code'), ('other', 'Other')], max_length=50),
        ),
    ]
