# Generated by Django 6.0.1 on 2026-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_site_uid_property_site_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='site_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, unique=True),
        ),
    ]
