# Generated by Django 6.0.1 on 2026-01-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_site_id'),
    ]

    operations = [
    ]
