# Generated by Django 6.0.1 on 2026-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20260112_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sor_site_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='strata_plan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
