# Generated by Django 6.0.1 on 2026-01-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_sor_site_id_property_strata_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['building_name', 'city', 'site_id'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='afss_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='certification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_commercial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_residential',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_description',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Residential / Commercial'), ('industrial', 'Industrial'), ('housing', 'Housing'), ('medical', 'Medical'), ('government', 'Government'), ('rural', 'Rural')], max_length=30),
        ),
    ]
