# Generated by Django 6.0.1 on 2026-01-29 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0010_alter_property_options_property_afss_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('asset_code_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('asset_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_assets', to='contenttypes.contenttype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_assets', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Asset',
                'verbose_name_plural': 'Property Assets',
                'ordering': ['property', 'asset_label', 'location', 'level', 'block', 'id'],
                'indexes': [models.Index(fields=['property', 'asset_code_content_type', 'asset_code_object_id'], name='properties__propert_eb11c8_idx')],
            },
        ),
    ]
