# Generated by Django 6.0.1 on 2026-01-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertyasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyasset',
            options={'ordering': ['property', 'asset_label', 'barcode', 'location', 'level', 'block', 'id'], 'verbose_name': 'Property Asset', 'verbose_name_plural': 'Property Assets'},
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
