# Generated by Django 6.0.1 on 2026-01-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0012_alter_propertyasset_options_propertyasset_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyasset',
            options={'ordering': ['property', 'asset_label', 'location', 'level', 'block', 'id'], 'verbose_name': 'Property Asset', 'verbose_name_plural': 'Property Assets'},
        ),
        migrations.AddIndex(
            model_name='propertyasset',
            index=models.Index(fields=['property', 'barcode'], name='properties__propert_cfd56a_idx'),
        ),
    ]
