# Generated by Django 6.0.1 on 2026-01-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_propertyasset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyasset',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Asset barcode/QR identifier (unique if provided).', max_length=100, null=True, unique=True),
        ),
    ]
