# Generated by Django 6.0.1 on 2026-01-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_name_customer_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-is_primary', 'name']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['site_name']},
        ),
    ]
