# Generated by Django 6.0.1 on 2026-01-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_contact_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accounting_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique ID created when linked to an accounting API at a later stage.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_type',
            field=models.CharField(choices=[('FACTORED', 'Factored'), ('NON_FACTORED', 'Non Factored'), ('CASH', 'Cash'), ('BARTERCARD', 'Bartercard')], db_index=True, default='FACTORED', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='System generated unique ID created when the client is created.', max_length=12),
        ),
    ]
