# Generated by Django 6.0.1 on 2026-01-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_accounting_id_customer_billing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accounting_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique ID created when linked to an accounting API at a later stage.', max_length=64, null=True),
        ),
    ]
