# Generated by Django 6.0.1 on 2026-01-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('legal_company_name', models.CharField(blank=True, max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_abn', models.CharField(blank=True, max_length=50)),
                ('company_acn', models.CharField(blank=True, max_length=50)),
                ('accounts_phone', models.CharField(blank=True, max_length=50)),
                ('accounts_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profile',
            },
        ),
    ]
