# Generated by Django 6.0.1 on 2026-01-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('fire_safety_measure', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
    ]
