# Generated by Django 6.0.1 on 2026-01-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='frequency',
        ),
        migrations.AddField(
            model_name='code',
            name='visits_per_year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Annual (1 / year)'), (2, 'Every 6 Months (2 / year)'), (4, 'Quarterly (4 / year)'), (12, 'Monthly (12 / year)')], default=1, help_text='Number of visits per year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='fire_safety_measure',
            field=models.CharField(max_length=255),
        ),
    ]
