# Generated by Django 6.0.1 on 2026-01-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_remove_code_frequency_code_visits_per_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='code',
            name='fire_safety_measure',
        ),
        migrations.RemoveField(
            model_name='code',
            name='visits_per_year',
        ),
        migrations.AddField(
            model_name='code',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
