# Generated by Django 6.0.1 on 2026-01-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_defectcode_remove_code_fire_safety_measure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defectcode',
            options={},
        ),
        migrations.RemoveField(
            model_name='code',
            name='description',
        ),
        migrations.RemoveField(
            model_name='defectcode',
            name='active',
        ),
        migrations.AddField(
            model_name='code',
            name='fire_safety_measure',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='code',
            name='visits_per_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='defectcode',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='defectcode',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
