# Generated by Django 6.0.1 on 2026-01-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_alter_defectcode_options_remove_code_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['code'], 'verbose_name': 'EFSM Code', 'verbose_name_plural': 'EFSM Codes'},
        ),
        migrations.AlterModelOptions(
            name='defectcode',
            options={'ordering': ['code'], 'verbose_name': 'Defect Code', 'verbose_name_plural': 'Defect Codes'},
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='fire_safety_measure',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='code',
            name='visits_per_year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='defectcode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='defectcode',
            name='description',
            field=models.TextField(),
        ),
    ]
