# Generated by Django 6.0.1 on 2026-01-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_alter_code_options_alter_defectcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
