# Generated by Django 6.0.1 on 2026-01-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_alter_code_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Code',
                'verbose_name_plural': 'Asset Codes',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
