# Generated by Django 6.0.1 on 2026-01-12 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0007_assetcode_alter_code_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcode',
            name='description',
        ),
        migrations.AddField(
            model_name='assetcode',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcode',
            name='equipment',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcode',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, help_text='Times per year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetcode',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Asset Code UID'),
        ),
    ]
