# Generated by Django 6.0.1 on 2026-01-12 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0008_remove_assetcode_description_assetcode_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dropdown List',
                'verbose_name_plural': 'Dropdown Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, default='', max_length=140)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('dropdown_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='codes.dropdownlist')),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent option for dependent lists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='codes.dropdownoption')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('dropdown_list', 'label')},
            },
        ),
        migrations.AlterField(
            model_name='assetcode',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='codes.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='assetcode',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_equipment', to='codes.dropdownoption'),
        ),
    ]
