# Generated by Django 6.0.1 on 2026-01-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0009_dropdownlist_dropdownoption_alter_assetcode_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropdownoption',
            options={'ordering': ['label']},
        ),
        migrations.RemoveField(
            model_name='dropdownoption',
            name='sort_order',
        ),
    ]
