# Generated by Django 6.0.1 on 2026-01-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0010_alter_dropdownoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropdownoption',
            options={'ordering': ['label'], 'verbose_name': 'Dropdown Option', 'verbose_name_plural': 'Dropdown Options'},
        ),
    ]
