# Generated by Django 6.0.1 on 2026-01-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0011_alter_dropdownoption_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Field',
                'verbose_name_plural': 'Asset Fields',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='assetcode',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic fields imported from Excel (only non-empty values stored).'),
        ),
        migrations.AlterField(
            model_name='assetcode',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, help_text='Times per year'),
        ),
    ]
