# Generated by Django 6.0.1 on 2026-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0012_assetfield_assetcode_attributes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dropdownoption',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dropdownoption',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('dropdown_list', 'label'), name='uq_dropdownoption_list_label_parent_null'),
        ),
        migrations.AddConstraint(
            model_name='dropdownoption',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('dropdown_list', 'parent', 'label'), name='uq_dropdownoption_list_parent_label_parent_not_null'),
        ),
    ]
