# Generated by Django 6.0.1 on 2026-01-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0013_alter_dropdownoption_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcode',
            name='optional_fields',
            field=models.ManyToManyField(blank=True, help_text='Which optional fields apply to this Asset Code type.', related_name='asset_codes', to='codes.assetfield'),
        ),
        migrations.AlterField(
            model_name='assetcode',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic values imported from Excel (only non-empty values stored).'),
        ),
    ]
