# Generated by Django 6.0.1 on 2026-01-30 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0014_assetcode_optional_fields_alter_assetcode_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcode',
            name='optional_fields',
        ),
        migrations.AlterField(
            model_name='assetcode',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic fields imported from Excel (only non-empty values stored).'),
        ),
        migrations.CreateModel(
            name='EquipmentOptionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=list, help_text='Allowed dropdown values for this field (strings).')),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_fields', to='codes.dropdownoption')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_fields', to='codes.assetfield')),
            ],
            options={
                'verbose_name': 'Equipment Optional Field',
                'verbose_name_plural': 'Equipment Optional Fields',
                'constraints': [models.UniqueConstraint(fields=('equipment', 'field'), name='uq_equipment_optional_field_equipment_field')],
            },
        ),
    ]
