# Generated by Django 6.0.1 on 2026-01-25 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QBOSyncQueue',
        ),
        migrations.RenameField(
            model_name='qboconnection',
            old_name='access_token_expires_at',
            new_name='expires_at',
        ),
        migrations.RemoveField(
            model_name='qboconnection',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='qboconnection',
            name='name',
        ),
        migrations.AlterField(
            model_name='qboconnection',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qboconnection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qboconnection',
            name='realm_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='qboconnection',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
