# Generated by Django 6.0.1 on 2026-01-26 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbo', '0002_delete_qbosyncqueue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qboconnection',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='qboconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qboconnection',
            name='realm_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='qboconnection',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='QBOObjectMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Account', 'Account'), ('Customer', 'Customer'), ('Item', 'Item'), ('Invoice', 'Invoice'), ('Payment', 'Payment')], max_length=20)),
                ('qbo_id', models.CharField(max_length=50)),
                ('local_app', models.CharField(blank=True, default='', max_length=50)),
                ('local_model', models.CharField(blank=True, default='', max_length=50)),
                ('local_pk', models.CharField(blank=True, default='', max_length=50)),
                ('qbo_sync_token', models.CharField(blank=True, default='', max_length=50)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'qbo_id'), name='uniq_qbo_object_by_type_and_id')],
            },
        ),
    ]
