# Generated by Django 6.0.1 on 2026-01-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Internal name (e.g. Service Quotation - Standard). If blank, it will auto-fill from Subject.', max_length=120),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('customer', 'Customer'), ('property', 'Property'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='cc',
            field=models.CharField(blank=True, default='', help_text='Comma-separated emails (supports placeholders)', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='to',
            field=models.CharField(blank=True, default='', help_text='Comma-separated emails (supports placeholders)', max_length=500),
        ),
    ]
