# Generated by Django 6.0.1 on 2026-01-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_emailtemplate_is_active_emailtemplate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='property',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='quotation',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
