# Generated by Django 6.0.1 on 2026-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='accepted_at',
        ),
        migrations.AddField(
            model_name='quotation',
            name='accepted_by_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quotation',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
