# Generated by Django 6.0.1 on 2026-01-22 04:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_remove_quotation_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='calc_afss_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_hours_annual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_hours_half',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_hours_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_men_annual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_men_half',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_men_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_price_annual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_price_half',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_price_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_visits_annual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_visits_half',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calc_visits_month',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
