# Generated by Django 6.0.1 on 2026-01-27 23:07

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0011_alter_dropdownoption_options'),
        ('quotations', '0005_quotation_calc_afss_charge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('quotation', 'position'), name='uniq_quotation_item_position'),
        ),
    ]
