# Generated by Django 6.0.1 on 2026-01-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_alter_quotationitem_options_quotationitem_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quotationitem',
            name='uniq_quotation_item_position',
        ),
    ]
