# Generated by Django 6.0.1 on 2026-01-28 06:35

import django.db.models.deletion
import quotations.models
from django.conf import settings
from django.db import migrations, models


# Generated by Django 6.0.1 on 2026-01-27 23:XX


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0006_alter_quotationitem_options_quotationitem_position_and_more"),
        # keep any other dependencies that were already here (if any)
    ]

    operations = [
        # keep ALL your existing operations exactly as-is below
    ]


    operations = [
        migrations.CreateModel(
            name='QuotationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_comments', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to=quotations.models.quotation_correspondence_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='quotations.quotation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_correspondence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
